const popular = [
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
  {
    item1: "Shirt(Launder and Press)",
    price1: 1250,
    item2: "Shirt(Launder and Press)",
    price2: 1250,
    item3: "Shirt(Launder and Press)",
    price3: 1250,
    item4: "Shirt(Launder and Press)",
    price4: 1250,
    item5: "Shirt(Launder and Press)",
    price5: 1250,
    item6: "Shirt(Launder and Press)",
    price6: 1250,
    item7: "Shirt(Launder and Press)",
    price7: 1250,
    item8: "Shirt(Launder and Press)",
    price8: 1250,
  },
];
const popular1 = [
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  {
    item: "Shirt(Launder and Press)",
    price: 1250,
  },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
  // {
  //   item: "Shirt(Launder and Press)",
  //   price: 1250,
  // },
];
const aparel1 = [
  {
    item1a: "Shirt(Launder and Press)",
    price1a: 1250,
  },
  {
    item2a: "Shirt(Launder and Press)",
    price2a: 1250,
  },
  {
    item3a: "Shirt(Launder and Press)",
    price3a: 1250,
  },
  {
    item4a: "Shirt(Launder and Press)",
    price4a: 1250,
  },
  {
    item5a: "Shirt(Launder and Press)",
    price5a: 1250,
  },
  {
    item6a: "Shirt(Launder and Press)",
    price6a: 1250,
  },
  {
    item7a: "Shirt(Launder and Press)",
    price7a: 1250,
  },
  {
    item8a: "Shirt(Launder and Press)",
    price8a: 1250,
  },
];
const aparel2 = [
  {
    item1b: "Shirt(Launder and Press)",
    price1b: 1250,
  },
  {
    item2b: "Shirt(Launder and Press)",
    price2b: 1250,
  },
  {
    item3b: "Shirt(Launder and Press)",
    price3b: 1250,
  },
  {
    item4b: "Shirt(Launder and Press)",
    price4b: 1250,
  },
  {
    item5b: "Shirt(Launder and Press)",
    price5b: 1250,
  },
  {
    item6b: "Shirt(Launder and Press)",
    price6b: 1250,
  },
  {
    item7b: "Shirt(Launder and Press)",
    price7b: 1250,
  },
  {
    item8b: "Shirt(Launder and Press)",
    price8b: 1250,
  },
];

export const people = [
  {
    img: "./img/laundry/clothes-4617456_1280.png",
    title: "product manager",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis? `,
  },
  {
    img: "./img/laundry/clothes-4617456_1280.pn",
    title: "developer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
  {
    img: "./img/laundry/daniele-bissoli-u25sfT6lv-Q-unsplash.jpg",
    title: "designer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
  {
    img: "./img/laundry/pxfuel.jpg",
    title: "designer",
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem quoeius recusandae officia voluptas sint deserunt dicta nihil nam omnis?`,
  },
];
